using ServiceEntity = Spot.Business.Api.Models.Service;

namespace Spot.Business.Api.Repositories;

/// <summary>
/// Persistence for a business's offered services (the services table). Named "ServiceOffering"
/// rather than "Service" so it doesn't read as a ServiceRepository/ServiceService next to the
/// application-layer services.
/// </summary>
public interface IServiceOfferingRepository
{
    /// <summary>
    /// Inserts <paramref name="service"/>. Its Id, CreatedAt and UpdatedAt are generated by the
    /// database and populated on the entity afterwards. Callers are expected to have already
    /// checked the parent business exists and belongs to the caller.
    /// </summary>
    Task CreateAsync(ServiceEntity service, CancellationToken ct = default);
}
