using System.Security.Cryptography;
using System.Text;

namespace Spot.Auth.Api.Services;

/// <summary>
/// Hashes refresh tokens with unsalted SHA-256.
/// </summary>
/// <remarks>
/// This is deliberately different from password hashing (which must use a slow, salted
/// algorithm like bcrypt/argon2 to resist brute-forcing a low-entropy human-chosen secret).
/// A refresh token is a high-entropy value generated by the server (256+ random bits, never
/// chosen or reused by a human), so a fast, unsalted cryptographic hash is the correct and
/// standard choice here: brute-forcing a random 256-bit value back from its hash is infeasible
/// regardless of hash speed, and a salt would only prevent precomputed-table attacks, which are
/// already meaningless against that much entropy. Using a slow hash instead would just make
/// every request that validates a refresh token unnecessarily expensive.
/// </remarks>
public sealed class Sha256RefreshTokenHasher : IRefreshTokenHasher
{
    public string Hash(string rawToken)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(rawToken);

        var bytes = SHA256.HashData(Encoding.UTF8.GetBytes(rawToken));
        return Convert.ToHexStringLower(bytes);
    }
}
